# Generated by Django 5.1.7 on 2025-03-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Book_name')),
                ('author', models.CharField(max_length=100, verbose_name='authoe')),
                ('description', models.TextField(verbose_name='description')),
                ('image1', models.ImageField(upload_to='books/', verbose_name='image1')),
                ('image2', models.ImageField(upload_to='books/', verbose_name='image2')),
                ('image3', models.ImageField(upload_to='books/', verbose_name='image3')),
            ],
        ),
    ]
